Skrypt1;

options = optimoptions('ga',...
            'PopulationType', 'bitstring',...
            'PlotFcn', {@gaplotbestf, @gaplotbestindiv, @outputfun},...
            'MaxGenerations', 100,...
            'MaxStallGenerations', 30,...
            'PopulationSize', 200,...
            'EliteCount', 1,...
            'SelectionFcn', {@selectionroulette},...
            'CrossoverFcn', {@crossoverscattered},...
            'CrossoverFraction', 0.5,...
            'MigrationFraction', 0,...
            'MutationFcn', {@mutationuniform, 0.05});

[vector, maxValue] = ga(@(x)fun(x, weights, scores, W),32,[],[],[],[],[],[],[],[], options); % invoking the solver with the appropriate settings (using the genetic algorithm)
fprintf("Solution = " + num2str(vector) + "\n");
fprintf("Total weight = " + sum(vector*weights) + "\n");
fprintf("Total score = " + sum(vector*scores) + "\n");
